create user proxy_router identified by proxy_router;
grant dba to proxy_router; 

CREATE TABLE ACTIVITY_LOG
    (
        ACTIVITY_LOG_ID NUMBER NOT NULL,
        REQUEST_TIME TIMESTAMP(6),
		RESPONSE_TIME TIMESTAMP(6),
        REQUEST_XML CLOB,
		RESPONSE_XML CLOB,
		SOURCE_IP VARCHAR2(250),
		DESTINATION_URL VARCHAR2(250),
        PRIMARY KEY (ACTIVITY_LOG_ID)
    );
	
CREATE SEQUENCE  "ACTIVITY_LOG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE
	
CREATE TABLE REQUEST_ROUTER
    (
        REQUEST_ROUTER_ID NUMBER NOT NULL,
		CONTEXT_PATH VARCHAR2(250),
		HANDLER_CLASS VARCHAR2(250),
		IS_ACTIVE NUMBER(1) DEFAULT 0 NOT NULL,
        PRIMARY KEY (REQUEST_ROUTER_ID)
    );
    
INSERT INTO REQUEST_ROUTER (REQUEST_ROUTER_ID, CONTEXT_PATH, HANDLER_CLASS, IS_ACTIVE) values (1, '/test', 'com.rizstien.proxy.controller.ProxyHandler', 1);

